# Generated by Django 4.1.4 on 2023-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='people',
            name='images',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
