# Generated by Django 4.1.4 on 2023-01-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_image_site_photo_alter_people_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='images',
        ),
    ]
